[tool.poetry]
name = "agentx"
version = "0.1.0"
description = "The Ultimate Modular Autonomous Multi AI Agent Framework."
authors = ["DecisionFacts AI <prabhu@decisionfacts.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
pydantic = "^2.8.2"
langchain = "^0.2.14"
boto3 = "^1.35.8"
langchain-openai = "0.1.23"
sqlalchemy = "^2.0.32"
psycopg2-binary = "^2.9.9"
pymysql = "^1.1.1"
oracledb = "^2.4.1"
pymssql = "^2.3.1"
pytest = "^8.3.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
